name: athena-devcontainer

services:
  # Dev Container app service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development # 開発用ターゲットを指定
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    init: true
    command: sleep infinity
    expose:
      - '3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URI=postgres://postgres@postgres:5432/payload_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - athena-network

  postgres:
    image: postgres:16
    expose:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: payload_db # THIS MUST MATCH YOUR DB NAME IN .env
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payload_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - athena-network
    env_file:
      - .env

volumes:
  node_modules:
  postgres_data:


networks:
  athena-network:
    driver: bridge
